version: '3.7'
services:
  mqtt:
    container_name: mqtt
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MQTT_USERNAME: root
      MQTT_PASSWORD: pass
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped
    volumes:
      - ./configs/mosquitto/mosquitto-data:/mosquitto/data
      - ./configs/mosquitto/mosquitto-logs:/mosquitto/logs

  zigbee2mqtt:
    depends_on: 
      - mqtt
    container_name: zigbee2mqtt
    ports:
      - 8080:8080
    image: koenkk/zigbee2mqtt
    volumes:
      - ./configs/zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: unless-stopped
    environment:
      - TZ=America/Toronto

